<script setup lang="ts">
import { BookOpen, Plus, Trash2, X } from 'lucide-vue-next'
import { onMounted, ref } from 'vue'
import { api } from '@/api'
import { notice } from '@/shared/notice'
import { projectEntryRoute } from '@/shared/shortDramaProject'
import type { Novel } from '@/types'
const novels = ref<Novel[]>([]); const loading = ref(true); const creating = ref(false); const showCreate = ref(false); const form = ref({ name: '', author: '', description: '', content: '' })
async function load() { loading.value = true; try { novels.value = (await api.novels()).data.items } catch (error) { notice.error((error as Error).message) } finally { loading.value = false } }
async function create() { if (!form.value.name.trim()) return; creating.value = true; try { await api.createNovel(form.value); showCreate.value = false; form.value = { name: '', author: '', description: '', content: '' }; await load(); notice.success('项目已创建') } catch (error) { notice.error((error as Error).message) } finally { creating.value = false } }
async function remove(item: Novel) { if (!confirm(`删除「${item.name}」？`)) return; await api.deleteNovel(item.id); novels.value = novels.value.filter(value => value.id !== item.id) }
onMounted(load)
</script>
<template><main class="page"><header class="page-header"><div><span class="eyebrow">PROJECTS</span><h1>我的项目</h1><p>管理小说、剧本与视频创作空间</p></div><AppButton variant="primary" @click="showCreate = true"><Plus :size="16" />新建项目</AppButton></header><div v-if="loading" class="state">正在加载项目…</div><div v-else-if="novels.length" class="project-grid"><RouterLink v-for="item in novels" :key="item.id" :to="projectEntryRoute(item)" class="project-card"><div class="project-cover"><img v-if="item.cover" :src="item.cover" :alt="item.name"><BookOpen v-else :size="34" /></div><div><h3>{{ item.name }}</h3><p>{{ item.description || '暂无简介' }}</p><small>{{ item.author || '未署名' }} · {{ item.total_chapters || 0 }} 章</small></div><AppButton type="button" variant="danger" size="sm" icon-only aria-label="删除项目" @click.prevent="remove(item)"><Trash2 :size="15" /></AppButton></RouterLink></div><div v-else class="empty-state"><BookOpen :size="32" /><h3>暂无项目</h3><p>创建第一部小说短剧项目</p><AppButton variant="secondary" @click="showCreate = true">创建项目</AppButton></div><div v-if="showCreate" class="modal-backdrop" @click.self="showCreate = false"><form class="modal" @submit.prevent="create"><header><h2>新建项目</h2><AppButton type="button" variant="ghost" size="sm" icon-only @click="showCreate = false"><X :size="18" /></AppButton></header><label>项目名称<input v-model="form.name" required></label><label>作者<input v-model="form.author"></label><label>简介<textarea v-model="form.description" rows="3" /></label><label>小说正文<textarea v-model="form.content" rows="8" /></label><footer><AppButton type="button" variant="secondary" @click="showCreate = false">取消</AppButton><AppButton type="submit" variant="primary" :loading="creating">{{ creating ? '创建中…' : '创建项目' }}</AppButton></footer></form></div></main></template>
